### ISSUE TITLE
Upgrade to Django 2.2

### ISSUE THREAD

**Issue by cabarnes** [rovercode/rovercode-web#232]
[Django 2.2](https://docs.djangoproject.com/en/2.2/releases/2.2/) was recently released. It's the next LTS version. Django 1.11 will be supported for one more year.

**Comment by aninternetof** [comment]
Have you done an upgrade to 2.x before? Any idea how painful it will be?

**Comment by cabarnes** [comment]
No, I haven't. Probably the biggest change is dropping support for Python 2.x. But, since we're already on Python 3, that won't be an issue. Other changes don't seem that significant and are typical of a Django upgrade. This is a nice overview: https://eldarion.com/blog/2017/12/26/10-tips-upgrading-django-20/
