### ISSUE TITLE
Add tags to block-diagram model

### ISSUE THREAD

**Issue by aninternetof** [rovercode/rovercode-web#242]
We'd like to add the ability tag programs. Students might tag their programs "Lesson 1", or "Dead reckoning" or "Try with the lights off". Admins might tag a program "Featured" or "program of the day".

I was thinking that we'd add two groups of tags to the block-diagram model:
* `userTags` (settable only by the owner)
* `adminTags` (settable by any admin user)

These could be added to the model by a standard many-to-many relationship, or I think there are Django plugins to help, like [Taggit](https://django-taggit.readthedocs.io/en/latest/).

I think the API definition will need to be updated to allow filtering by these fields, too.

**Comment by cabarnes** [comment]
I'm thinking this should be case insensitive since case doesn't differentiate a descriptor like this

**Comment by cabarnes** [comment]
I think we should set minimum and maximum lengths for the tags. Something like 3 and 30?

**Comment by aninternetof** [comment]
Agreed. 30 seems right?

What about spaces? Allowed?

**Comment by cabarnes** [comment]
I think spaces would be allowed based on the examples in the description
