### ISSUE TITLE
Should use currently logged-in user as owner when registering rover

### ISSUE THREAD

**Issue by aninternetof** [rovercode/rovercode-web#86]
We need to add a `perform_create` to the [`RoverViewSet`](https://github.com/rovercode/rovercode-web/blob/development/mission_control/views.py#L63), similar to the one used by `BlockDiagramViewset`.
Then, mark the `owner` field as read-only in its serializer.

**Comment by pardegerman** [comment]
The changes in the feature branch for this issue seems to work as expected
